### ISSUE TITLE
get 403 error when register new account

### ISSUE THREAD

**Issue by keepsky** [kbss-cvut/fta-fmea-ui#672]
Hello folks,
I found this place while searching for FTA and FMEA tool on the internet and I success building the sources, and I'm able to start it. However, I got a CORS-related error as shown in the image below, so I would like to get help from you.
I just executed the commands below to start servces in local environment. I'm very beginner for spring boot and front-end domain as I'm embedded engineer.

npm install
npm run build
cd ./deploy/internal-auth
docker-compose up -d

![Image](https://github.com/user-attachments/assets/0eb07ac0-790a-4b62-af31-e86baa2ad529)

![Image](https://github.com/user-attachments/assets/87f16f9b-fa6b-411b-a7a7-9ebfb82cc9f0)

**Comment by blcham** [comment]
Hi,
not sure which guide you are trying to follow as you are combining execution of the frontend guide and execution of whole tool guide. 
If I follow  
[this guide](https://github.com/kbss-cvut/fta-fmea-ui/blob/main/README.md#running-complete-tool-in-docker)  I do not seem to have CORS issue:

![Image](https://github.com/user-attachments/assets/9e228e1c-e8d1-4c43-a5d7-bd1fb7e5dddf)


BTW, in the guide I changed port reference in previous commit.

**Comment by blcham** [comment]
@keepsky https://github.com/kbss-cvut/fta-fmea-ui/issues/673 should be resolved.

**Comment by keepsky** [comment]
@blcham , thanks for kind update.
I still have 401 error even after applying your changes #673 
Please see my snapshot and log below

[ff-iauth-demo-fta-fmea-server_log.txt](https://github.com/user-attachments/files/19728781/ff-iauth-demo-fta-fmea-server_log.txt)

![Image](https://github.com/user-attachments/assets/6b2d3218-21fb-4bc8-8aa4-213758aecbbc)

![Image](https://github.com/user-attachments/assets/4156613d-1900-4715-affa-a9c9316f477c)
[](url)

**Comment by kostobog** [comment]
Hi @keepsky, based on the log from your last post it seems that the docker container is still using the old docker image.

The simplest solution is to call the following command in the directory of the docker-compose file
`> docker pull `
This will download latest docker images published on github.

**Comment by keepsky** [comment]
Hi @blcham , Thanks for the guide and sorry for your inconvenience.
Actually I did update docker images as per your guide <docker compose pull> but it looks that my problem was not resolved.
Please kindly see the screenshots and attached log file.

![Image](https://github.com/user-attachments/assets/a528cc5a-a4e0-42e8-85ba-23416dd7b275)

![Image](https://github.com/user-attachments/assets/be155660-b4ba-4eb3-a513-1d4773559657)

[srckbss-cvutfta-fme_20250417.txt](https://github.com/user-attachments/files/19786674/srckbss-cvutfta-fme_20250417.txt)

**Comment by keepsky** [comment]
Hi @blcham, I tried keycloak-auth as well but it seems not to provide account register page so that I can't create my account.

![Image](https://github.com/user-attachments/assets/a25386af-d5ed-4007-b298-a6e3cb972819)

[ff-kauth-demo-fta-fmea-server_log_20250417.txt](https://github.com/user-attachments/files/19786737/ff-kauth-demo-fta-fmea-server_log_20250417.txt)

**Comment by kostobog** [comment]
@keepsky @blcham 
I fixed the issue #673 and successfully managed registering and signing in with a new user with the latest docker images in `internal-auth` docker deployment.
